name: Run Cypress Tests On Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Install Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install cypress
      - name: Run Cypress Tests
        run: npm run test:cypress
